version: '3.4'

services:
  couchbase:
    image: couchbase
    volumes:
    - "./couchbase:/opt/couchbase/var" # local folder where couchbase data stored
    ports:
    - "8091:8091" # Allows local access to mgmt UI
  hellomicroservice:
    image: ${DOCKER_REGISTRY-}hellomicroservice
    build:
      context: .
      dockerfile: HelloServiceAspNetCore/Dockerfile
    environment:
      Couchbase__Servers__0: http://couchbase:8091/ # Reference to the "couchbase" service name on line 4
    depends_on:
    - couchbase # Reference to the "couchbase" service name on line 4
    command: ["./wait-for-it.sh", "http://couchbase:8091"]